[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "prekick"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy==2.5.3",
    "pandas==3.0.6",
    "requests==2.34.2",
    "scipy==1.18.1",
    "streamlit==1.63.0"
]

[dependency-groups]
test = [
    "pytest==9.1.1"
]
